Algoritmo "imprimir_numeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
x: inteiro
flag: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para x de 1 ate 8 passo 1 faca
     escreva("BLACK ")

fimpara
Fimalgoritmo